
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (1, 'Stark, Mueller and Witting', '219 Kennedy Hill', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (2, 'Kilback Group', '47454 Gulseth Pass', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (3, 'Pacocha-Jacobi', '69 Myrtle Street', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (4, 'Lynch, Windler and Hilll', '80 International Center', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (5, 'Hauck LLC', '3792 Maple Wood Crossing', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (6, 'Adams, Ritchie and Moen', '8402 Morningstar Parkway', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (7, 'Walter Group', '0 Swallow Crossing', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (8, 'West and Sons', '0257 Debra Road', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (9, 'Ritchie and Sons', '9049 Talisman Way', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (10, 'Eichmann Group', '3616 Hudson Alley', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (11, 'Ziemann, Grimes and Hoeger', '599 Dapin Lane', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (12, 'Cassin Inc', '444 Londonderry Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (13, 'Effertz-Dicki', '6 Gulseth Trail', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (14, 'Casper-Legros', '1324 Gale Center', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (15, 'Haley-White', '13636 Sommers Trail', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (16, 'Mante and Sons', '55103 West Parkway', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (17, 'O''Keefe, Adams and Rippin', '8108 Schiller Trail', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (18, 'Medhurst Inc', '413 Brentwood Center', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (19, 'Bayer LLC', '8 Comanche Park', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (20, 'Krajcik-Jast', '21 Beilfuss Terrace', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (21, 'Goodwin, Kassulke and Dare', '124 Cherokee Trail', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (22, 'Nienow, Hammes and McClure', '37 Mayfield Way', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (23, 'Kulas, Von and Homenick', '9 Thompson Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (24, 'Jerde, Stark and Harvey', '729 Fieldstone Terrace', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (25, 'Baumbach-Mayert', '17302 Sugar Center', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (26, 'Cronin-Weissnat', '1 Scofield Alley', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (27, 'Mitchell, Swaniawski and Langosh', '7 Mesta Terrace', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (28, 'Halvorson Inc', '2586 Harbort Hill', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (29, 'Powlowski-Dickens', '583 Hoffman Avenue', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (30, 'Buckridge-Kilback', '60386 Prairie Rose Point', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (31, 'Rutherford Inc', '3 Waubesa Parkway', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (32, 'Hilpert-Nikolaus', '7112 Straubel Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (33, 'Wunsch-Gerlach', '44 Kingsford Avenue', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (34, 'Volkman, Strosin and Toy', '78804 Lerdahl Lane', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (35, 'Skiles, Predovic and Streich', '14841 Lillian Road', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (36, 'Ortiz and Sons', '470 Ruskin Street', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (37, 'Wisoky, Champlin and Kub', '15 Brentwood Terrace', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (38, 'King-Emmerich', '229 Golf Course Pass', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (39, 'Gerhold Inc', '566 Crest Line Center', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (40, 'Lind-Abernathy', '28321 Ramsey Lane', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (41, 'Gerhold, Wunsch and Douglas', '24 Haas Trail', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (42, 'Fahey-Williamson', '1 Schurz Lane', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (43, 'Mohr Group', '32 Lighthouse Bay Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (44, 'Ward LLC', '33307 Dovetail Hill', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (45, 'Gottlieb, Klein and Kris', '1 Knutson Point', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (46, 'Gulgowski, Raynor and Fay', '5000 Thackeray Plaza', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (47, 'Marquardt Inc', '3716 Acker Pass', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (48, 'Abernathy LLC', '2 Coolidge Plaza', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (49, 'Bartell, Greenholt and Keeling', '27 Carey Center', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (50, 'Gutkowski LLC', '73994 Atwood Drive', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (51, 'Stiedemann and Sons', '74488 Bobwhite Place', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (52, 'Kertzmann and Sons', '33 Northport Junction', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (53, 'Harber, Kutch and Deckow', '69064 Michigan Place', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (54, 'Douglas Group', '38171 Schmedeman Circle', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (55, 'Zulauf-McDermott', '8 Loeprich Place', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (56, 'Johnston Group', '57981 Lyons Center', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (57, 'Koss, Homenick and Thompson', '212 Red Cloud Terrace', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (58, 'Howell, Kshlerin and Durgan', '17056 La Follette Road', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (59, 'Green and Sons', '64158 Golf View Park', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (60, 'Harber Inc', '37 Prairieview Avenue', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (61, 'Armstrong Group', '20 Talmadge Road', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (62, 'Anderson-O''Reilly', '103 Carberry Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (63, 'Hermann, Connelly and Smith', '9367 Warner Plaza', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (64, 'Schmeler and Sons', '4047 Hallows Trail', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (65, 'Macejkovic Group', '60772 Duke Hill', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (66, 'Lindgren-Rohan', '08 Comanche Point', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (67, 'Goyette, Crist and Doyle', '57438 Manitowish Alley', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (68, 'Zemlak-Bogisich', '197 Karstens Park', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (69, 'Gleason, Kozey and Halvorson', '38 Truax Park', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (70, 'Stark Group', '0714 Moland Point', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (71, 'Bosco-Haag', '62 1st Center', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (72, 'Bergnaum and Sons', '6 Sommers Circle', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (73, 'Marvin-Jones', '0 Rigney Court', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (74, 'Wolf and Sons', '71 Mosinee Crossing', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (75, 'Graham Inc', '29490 Vera Avenue', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (76, 'Reinger, Pagac and Quigley', '6 Express Hill', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (77, 'McGlynn Group', '4 Farragut Hill', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (78, 'Rogahn Inc', '0904 Roxbury Road', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (79, 'Terry, Marks and Harber', '1 Express Trail', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (80, 'Feest, Homenick and Hayes', '12 Ramsey Trail', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (81, 'Wisoky-Stroman', '65 Doe Crossing Plaza', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (82, 'Schaefer Inc', '61 Magdeline Parkway', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (83, 'Rempel, Hand and Bashirian', '3 Elmside Plaza', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (84, 'Kozey and Sons', '64735 Meadow Ridge Street', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (85, 'Wisoky Group', '134 3rd Plaza', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (86, 'Berge, Abshire and Padberg', '167 Moose Center', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (87, 'Daniel Group', '05526 Red Cloud Lane', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (88, 'Conroy, Hodkiewicz and Monahan', '798 Straubel Crossing', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (89, 'Ankunding LLC', '48287 Waubesa Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (90, 'Bernier-Stracke', '8 Chive Way', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (91, 'Littel, Mayer and Huel', '821 Lindbergh Avenue', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (92, 'O''Conner Inc', '6519 Columbus Junction', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (93, 'Bahringer, Jaskolski and Purdy', '946 Montana Street', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (94, 'Lowe Group', '5152 Spohn Place', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (95, 'Carroll, Conroy and Lubowitz', '530 Mcguire Parkway', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (96, 'Goldner, Parker and Beatty', '174 Mcbride Trail', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (97, 'Wisoky, Grady and Thompson', '70 Becker Pass', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (98, 'Raynor LLC', '8998 Orin Trail', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (99, 'Runolfsson, McDermott and Schaefer', '11 Hudson Way', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (100, 'Konopelski, Leannon and Flatley', '22 Crest Line Place', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (101, 'Kulas, Hoeger and Boehm', '5 Loomis Lane', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (102, 'Purdy-Gleason', '9110 Lunder Terrace', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (103, 'Purdy-Champlin', '81834 Bunting Alley', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (104, 'Kuhlman LLC', '2 Londonderry Point', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (105, 'Kris and Sons', '68 Hermina Terrace', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (106, 'Hyatt-Schowalter', '80 New Castle Parkway', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (107, 'Daugherty-Gottlieb', '71361 Larry Trail', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (108, 'Herman-Ullrich', '798 Pawling Center', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (109, 'Bailey, Larkin and Thiel', '6107 Ronald Regan Parkway', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (110, 'Block, Heathcote and Reichel', '60934 Scofield Point', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (111, 'Crooks-Berge', '1 Hintze Street', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (112, 'Orn LLC', '72953 Tennessee Parkway', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (113, 'Mayert Inc', '53566 Paget Place', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (114, 'Wunsch, Grady and Swaniawski', '71 Meadow Vale Road', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (115, 'Marks-Wehner', '2085 Darwin Circle', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (116, 'Stark-Lemke', '49 Prentice Hill', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (117, 'Williamson, Bartell and DuBuque', '25 Maywood Point', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (118, 'Jast-Bashirian', '0803 Superior Alley', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (119, 'Volkman and Sons', '99424 Sutteridge Parkway', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (120, 'Bruen-Brekke', '8437 Anthes Way', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (121, 'Bayer, Hermann and Hintz', '16 Starling Parkway', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (122, 'Wolff-Olson', '91 Mesta Point', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (123, 'Mayert, Mann and Borer', '59439 Riverside Pass', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (124, 'White LLC', '780 Texas Court', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (125, 'Nader-Hirthe', '35935 Blaine Junction', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (126, 'Paucek LLC', '39 Rigney Park', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (127, 'Kuhn and Sons', '6179 Shopko Hill', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (128, 'Doyle, Daniel and Jaskolski', '7 Dexter Way', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (129, 'Jacobi, O''Connell and Koepp', '76929 Pawling Street', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (130, 'Cruickshank, Flatley and Bayer', '17 Holy Cross Avenue', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (131, 'Emard-Schaefer', '3696 Nelson Street', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (132, 'Franecki, Howell and Aufderhar', '68 Larry Terrace', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (133, 'Cormier-Purdy', '30543 Thompson Circle', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (134, 'Kertzmann, Jakubowski and Emmerich', '48247 Golf View Center', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (135, 'Stoltenberg, Douglas and Marvin', '41871 Lakewood Terrace', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (136, 'Altenwerth-O''Hara', '0225 Mockingbird Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (137, 'Crona, Gibson and Braun', '441 Mccormick Park', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (138, 'Prosacco and Sons', '18 Towne Way', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (139, 'Ziemann LLC', '7162 Declaration Way', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (140, 'Ebert Inc', '1 Dunning Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (141, 'Franecki Inc', '670 Tomscot Point', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (142, 'Flatley-Grady', '45148 Shopko Hill', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (143, 'Green, Larson and Rice', '3429 Hoffman Road', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (144, 'Emmerich Group', '40 Hintze Drive', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (145, 'Dietrich, Purdy and Kulas', '24 Birchwood Drive', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (146, 'Raynor-Torp', '9 Judy Park', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (147, 'Roberts-Christiansen', '9 Fuller Terrace', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (148, 'Stracke-Lang', '76770 Morningstar Street', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (149, 'Hamill LLC', '8 Sage Parkway', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (150, 'Goodwin-Lakin', '75947 Esker Plaza', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (151, 'Renner LLC', '9148 Brown Street', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (152, 'Lehner, Howe and Conn', '1562 Corben Park', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (153, 'Kreiger-Gleichner', '3322 Gale Way', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (154, 'Sporer-Muller', '2545 Kenwood Point', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (155, 'Ankunding-Kuhn', '8 Sauthoff Crossing', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (156, 'Kutch, Leannon and Armstrong', '0951 Colorado Drive', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (157, 'Ratke-Volkman', '8529 Graceland Street', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (158, 'Torphy LLC', '95 Warbler Plaza', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (159, 'Spencer Inc', '616 Stone Corner Center', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (160, 'Leannon Inc', '7816 Victoria Drive', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (161, 'MacGyver, Herman and Sporer', '0131 Straubel Parkway', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (162, 'Denesik LLC', '540 Aberg Center', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (163, 'Mante, Hilll and Steuber', '923 Roth Road', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (164, 'Dach, Yundt and Buckridge', '6630 Barby Park', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (165, 'Barton LLC', '2 Green Drive', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (166, 'Watsica Group', '38701 Kinsman Alley', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (167, 'Streich Group', '25 Bunker Hill Junction', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (168, 'Friesen LLC', '13710 Mosinee Parkway', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (169, 'Little Group', '35740 Graceland Point', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (170, 'Bashirian, DuBuque and Haley', '75302 Starling Point', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (171, 'Crist Inc', '826 Muir Hill', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (172, 'Ebert Inc', '5 Blackbird Place', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (173, 'Watsica and Sons', '21831 Northview Circle', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (174, 'Senger, Wolff and Crist', '00261 Lawn Place', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (175, 'Boehm Inc', '1 Kensington Circle', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (176, 'Becker-Reynolds', '92 Vernon Avenue', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (177, 'Windler, Bernhard and Harber', '2281 Mcguire Alley', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (178, 'Ryan-Schuppe', '05 Duke Avenue', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (179, 'Nikolaus, Feest and Gleichner', '41 Bluejay Crossing', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (180, 'Littel-Sawayn', '4 Nancy Place', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (181, 'Mitchell-Kemmer', '9 Bartelt Center', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (182, 'Swaniawski-Mills', '250 Eagan Road', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (183, 'Powlowski, Dietrich and Considine', '40 Schurz Center', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (184, 'Dooley-Friesen', '394 Prairie Rose Crossing', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (185, 'Blick, Ruecker and Weber', '02 Kingsford Pass', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (186, 'O''Kon and Sons', '90589 Barby Pass', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (187, 'Waters-Hermann', '15470 Huxley Point', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (188, 'Hauck and Sons', '90 Rowland Way', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (189, 'O''Keefe-Lindgren', '171 Ridgeview Drive', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (190, 'Kuhn, Bergnaum and Boehm', '30954 Pierstorff Drive', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (191, 'Keebler and Sons', '2 Sullivan Pass', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (192, 'Durgan LLC', '35 Reindahl Plaza', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (193, 'Metz, Harvey and Lockman', '77821 Schiller Lane', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (194, 'Greenholt, Hudson and Dooley', '8474 Brentwood Trail', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (195, 'Hudson LLC', '990 Duke Point', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (196, 'Trantow Inc', '80557 Oriole Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (197, 'D''Amore, Fay and Von', '423 Anhalt Court', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (198, 'Macejkovic and Sons', '37650 Twin Pines Center', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (199, 'Mante, Hackett and McCullough', '113 Kenwood Court', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (200, 'Little-Swift', '8 Dayton Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (201, 'Kuhic, Bahringer and Moore', '36 Hansons Plaza', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (202, 'Spencer-Berge', '6 Independence Alley', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (203, 'Murazik-Hayes', '817 Debra Point', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (204, 'Fahey-Hahn', '68281 Atwood Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (205, 'Aufderhar and Sons', '768 American Junction', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (206, 'Zieme-Haley', '593 Butternut Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (207, 'Feeney-Rau', '0 Cottonwood Center', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (208, 'Kutch-MacGyver', '4 Blaine Court', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (209, 'Will, Langworth and Swift', '63 Kennedy Road', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (210, 'Vandervort LLC', '8526 Kedzie Terrace', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (211, 'Barrows-Lueilwitz', '1176 Barnett Center', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (212, 'Trantow Group', '62 Pond Hill', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (213, 'Yost, Daugherty and Miller', '2 Calypso Terrace', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (214, 'Monahan-Rempel', '27546 Oxford Park', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (215, 'Lehner Inc', '27635 Holmberg Plaza', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (216, 'Schoen and Sons', '23 Old Shore Plaza', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (217, 'Bode, Herzog and Kunde', '83 Colorado Parkway', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (218, 'Schimmel, Olson and Marquardt', '12140 Namekagon Terrace', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (219, 'Dibbert Group', '84668 Ridgeway Center', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (220, 'Lind-Barton', '172 Oriole Plaza', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (221, 'O''Kon, Tillman and Hayes', '32 Novick Trail', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (222, 'Bogan-Parker', '973 Iowa Lane', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (223, 'Corwin LLC', '6 Acker Hill', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (224, 'Marvin Group', '968 Superior Park', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (225, 'Waelchi, Gutkowski and Herman', '631 Pawling Plaza', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (226, 'Koepp-Ankunding', '01 East Way', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (227, 'Haley, Strosin and Bode', '00701 Glendale Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (228, 'Deckow, Hilpert and Stroman', '21544 Calypso Road', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (229, 'Mills-Zulauf', '141 Talmadge Alley', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (230, 'Kiehn-Harvey', '067 Surrey Trail', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (231, 'Fritsch-Kovacek', '247 Arizona Avenue', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (232, 'Larkin and Sons', '00 Fallview Street', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (233, 'Kovacek, Sauer and Nolan', '9237 Division Plaza', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (234, 'Mante Group', '7 Lerdahl Point', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (235, 'Pouros Inc', '3 Buhler Junction', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (236, 'Davis, Kris and Hayes', '79 Tony Park', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (237, 'Simonis-Johnson', '1834 Corben Parkway', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (238, 'Torphy, Dooley and Shields', '19 Ridgeway Drive', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (239, 'Kuhlman, Jakubowski and Schaden', '457 Atwood Trail', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (240, 'Strosin, Waters and Howell', '35 3rd Parkway', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (241, 'Halvorson-Green', '17 Birchwood Center', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (242, 'Johnston, Streich and Toy', '183 Roxbury Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (243, 'Windler-Fay', '5546 Park Meadow Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (244, 'Connelly-Kuvalis', '32 Northridge Lane', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (245, 'Bartoletti, Klocko and Collier', '1302 Fieldstone Circle', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (246, 'Gerhold, Dibbert and Schmitt', '28 Colorado Avenue', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (247, 'Turner and Sons', '405 Hollow Ridge Avenue', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (248, 'Metz LLC', '71 Hansons Pass', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (249, 'Nienow, McClure and Nikolaus', '64911 Canary Street', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (250, 'DuBuque, Dach and Marvin', '09449 Buena Vista Court', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (251, 'Koepp and Sons', '01967 Kropf Plaza', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (252, 'Raynor, Hickle and Mohr', '093 Surrey Alley', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (253, 'Keebler-Little', '0719 Arkansas Terrace', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (254, 'Shanahan and Sons', '486 Steensland Street', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (255, 'Lind, Spinka and Dach', '400 Tony Avenue', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (256, 'Collins-Brown', '574 Sunnyside Plaza', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (257, 'Schamberger and Sons', '89862 Sutherland Avenue', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (258, 'Feil Group', '2 Crowley Way', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (259, 'Borer-Feest', '66 Harper Avenue', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (260, 'Cormier, Cruickshank and Herman', '036 Longview Hill', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (261, 'Davis Inc', '3138 Beilfuss Terrace', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (262, 'Witting Inc', '9726 Larry Circle', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (263, 'Waelchi, Wiegand and Schuster', '9 Arapahoe Lane', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (264, 'Towne, Bergnaum and Bergstrom', '44613 Elka Court', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (265, 'Bernhard, McLaughlin and Boyer', '95103 Walton Crossing', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (266, 'Rau Inc', '99 Dottie Pass', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (267, 'Douglas-Mueller', '43567 Crownhardt Park', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (268, 'Bechtelar, O''Keefe and Bechtelar', '249 Thompson Point', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (269, 'Boyer, Dicki and Borer', '766 Heath Trail', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (270, 'Leffler Inc', '6328 Northland Way', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (271, 'Cruickshank LLC', '0 Jackson Terrace', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (272, 'Murphy LLC', '89343 Haas Point', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (273, 'Corkery-DuBuque', '1 Bashford Center', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (274, 'Deckow LLC', '8 Sauthoff Circle', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (275, 'Klocko, Fay and Willms', '4 Merchant Drive', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (276, 'Kling, Feeney and Armstrong', '45145 Sherman Park', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (277, 'Blanda, Johns and Cruickshank', '9593 Eagle Crest Alley', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (278, 'Weimann, Roob and Stanton', '3 Roth Drive', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (279, 'Schuster Inc', '21314 Oxford Street', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (280, 'Bailey Group', '0226 Farragut Crossing', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (281, 'Quigley-Kling', '6 Thackeray Alley', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (282, 'Heathcote LLC', '9790 Darwin Street', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (283, 'Medhurst, Heller and Runte', '0255 Texas Plaza', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (284, 'Schultz, Larson and Hickle', '0280 Londonderry Alley', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (285, 'White Inc', '4 Garrison Plaza', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (286, 'Nader-Parisian', '2012 Gina Crossing', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (287, 'Miller, Hyatt and Bednar', '09 Golf Park', 'Rabat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (288, 'Bogisich and Sons', '7 Hollow Ridge Place', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (289, 'Wiegand-DuBuque', '12696 Eastlawn Point', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (290, 'Hermiston-Sporer', '4 Barby Place', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (291, 'MacGyver Inc', '1 Anthes Crossing', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (292, 'Heaney-Collins', '1 Swallow Trail', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (293, 'Fay-Bode', '803 Cody Parkway', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (294, 'Marquardt and Sons', '9 Hauk Avenue', 'agadir');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (295, 'Morar, Bergstrom and Powlowski', '45 3rd Plaza', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (296, 'Greenholt Inc', '0 Dorton Plaza', 'Casablanca');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (297, 'Adams LLC', '116 David Terrace', 'fes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (298, 'Kunde, Dickinson and Weissnat', '9085 Nobel Hill', 'Meknes');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (299, 'Doyle Inc', '959 Northridge Street', 'settat');
insert into AGENCES (IDAGENCE, NOMAGENCE, ADRESSE, VILLE) values (300, 'Kessler, Becker and Boehm', '8 Spohn Pass', 'agadir');
